models/urls.py
from django.urls import path

from . import views


app_name = 'model_of_phone'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:phone_name>/', views.model_of_phone, name='shell'),
    path('detail/<int:pk>', views.image_of_phone, name='image_of_phone')
]

phones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('models/', include('models.urls')),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models/admin.py
from django.contrib import admin

from .models import Phones, Type


@admin.register(Phones)
class PhonesAdmin(admin.ModelAdmin):
    search_fields = ('brand',)
    list_filter = ('brand', )


@admin.register(Type)
class TypeAdmin(admin.ModelAdmin):
    fields = (
        'name_of_model', 'phone', 'price', 'image'
    )
    list_display = ('id', 'name_of_model', 'phone', 'price', )
    search_fields = ('name_of_model', )

models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    name = 'models'

models/models.py
from django.db import models


class Phones(models.Model):
    brand = models.CharField(max_length=100)
    year_of_foundation = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.brand


class Type(models.Model):
    name_of_model = models.CharField(max_length=200)
    phone = models.ForeignKey(Phones,
                               on_delete=models.CASCADE,
                               related_name='types')
    price = models.IntegerField()
    start_of_sales = models.DateField()
    image = models.ImageField()

    def __str__(self):
        return self.name_of_model

models/tests.py
from django.test import TestCase

# Create your tests here.

models/views.py
from django.shortcuts import render, get_object_or_404

from .models import Phones


def index(request):
    phones = Phones.objects.order_by('brand')
    context = {'phones': phones}
    return render(request, 'index.html', context)


def model_of_phone(request, phone_name):
    query = {'brand': phone_name}
    phone = get_object_or_404(Phones, **query)

    context = {
        'phone': phone,
        'types': phone.types.all(),
        'class': phone_name.lower()
    }
    return render(request, 'model_of_phone.html', context)


def image_of_phone(request, pk):
    img = Type.objects.get(id=pk)
    data = {'id': img}
    return render(request, 'image_of_phone.html', data)

models/templates/image_of_phone.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"/>
    <title>Фото телефона</title>
</head>
<body>
{% for type in types %}
    <img src="{{ type.image.url }}"/>
{% endfor %}
</body>
</html>

models/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<title>Бренды телефонов</title>
<link rel="stylesheet" type="text/css" href="{% static 'models/style.css' %}" />
</head>
<body>
<h1>Бренды телефонов</h1>

{% if phones %}

    <ol>
        {% for phone in phones %}

            <h3>
                <li>
                    <a href="{% url 'model_of_phone:shell' phone.brand %}"
                       title="Дата создания {{ phone.year_of_foundation }}">

                        {{ phone.brand }}

                    </a>
                </li>
            </h3>


        {% endfor %}
    </ol>

{% endif %}
</body>
</html>

models/templates/model_of_phone.html
{% load static %}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
<link rel="stylesheet" type="text/css" href="{% static 'models/background_brand.css' %}"/>
<title>Модели</title>
{#</head>#}
<body class= {{ class }}>
<h1> Модели: {{ phone.brand }}</h1>

<ol>

{% for type in types %}

    <h2>
        <a href="{% url 'model_of_phone:image_of_phone' type.id %}">
            {{ type.name_of_model }}
        </a>
    </h2>
    <div>
        <img src="{{ type.image.url }}" width="240px"/>
    </div>
    <p>Цена - {{ type.price }} грн </p>

    <p>Старт продаж -  {{ type.start_of_sales }}</p>

{% endfor %}

</ol>
</body>
{#</html>#}